version: "3.9"

services:
  app:
    image: sangkips/quizbox:latest
    working_dir: /usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    networks:
      - quizbox_net
  db:
    image: postgres:15.1-alpine

    volumes:
      - quizbox_pg:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - quizbox_net
volumes:
  quizbox_pg:
  quizbox_app:

networks:
  quizbox_net:
