# Generated by Django 4.1.4 on 2022-12-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_rename_user_id_question_owner_tag_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="user_id",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="user_id",
            new_name="owner",
        ),
    ]
