# Generated by Django 4.1.4 on 2022-12-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_rename_user_id_answer_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
