# Generated by Django 4.1.4 on 2022-12-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_tag_created_at_tag_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="quetion_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.question",
            ),
        ),
    ]
