# Generated by Django 4.1.4 on 2022-12-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_alter_answer_question_id_alter_vote_quetion_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
