# Generated by Django 4.1.4 on 2023-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_question_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
