# Generated by Django 4.1.4 on 2023-02-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_alter_tag_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.tag",
            ),
        ),
    ]
