# Generated by Django 4.1.4 on 2023-02-04 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_alter_question_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
            ),
        ),
    ]
