# Generated by Django 4.1.4 on 2023-02-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_alter_answer_question_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="quetion_id",
            new_name="question_id",
        ),
    ]
