# Generated by Django 4.1.4 on 2022-12-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_picture",
            field=models.ImageField(default="avatar.jpeg", upload_to="profile_images"),
        ),
    ]
